---
openapi: 3.1.0
jsonSchemaDialect: https://json-schema.org/draft/2020-12/schema
info:
  title: eCH-0011 Personendaten – Demo API
  version: 0.1.0
servers:
  - url: https://api.example.org/v1

paths:
  /persons:
    get:
      summary: Liste von Personen (Demo)
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Person'

  /persons/{id}:
    get:
      summary: Person nach ID (Demo)
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'

components:
  schemas:
    Person:
      $ref: ../schemas/person/person.json
