openapi: 3.0.3
info:
  title: eCH-0011 Personendaten – Demo API
  version: 0.1.0
servers:
  - url: https://api.example.org/v1
paths:
  /persons:
    get:
      summary: Liste von Personen (Demo)
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "../schemas/person/person.json"
  /persons/{id}:
    get:
      summary: Person nach ID (Demo)
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "../schemas/person/person.json"
