name: Change Proposal (RFC)
description: Änderung/Erweiterung des Standards vorschlagen
labels: ["rfc","spec-change"]
body:
  - type: textarea
    id: context
    attributes:
      label: Kontext & Problem
  - type: textarea
    id: proposal
    attributes:
      label: Vorschlag
  - type: checkboxes
    id: impact
    attributes:
      label: Impact
      options:
        - label: Breaking Change
