name: Validate Schemas & OpenAPI

on:
  pull_request:
    paths:
      - "schemas/**"
      - "openapi/**"
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Repository auschecken
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Node.js einrichten
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # 3️⃣ CLI-Tools installieren
      - name: Install CLI tools
        run: |
          npm install -g @redocly/cli swagger-cli ajv-cli ajv-formats

      # 4️⃣ OpenAPI prüfen (syntaktisch + Best-Practices)
      - name: Validate OpenAPI (swagger-cli + redocly)
        run: |
          echo "🔍 Validating OpenAPI specifications..."
          swagger-cli validate openapi/*.yaml
          # Lint gibt nur Hinweise; kein Build-Stop
          npx @redocly/cli lint openapi/*.yaml || true

      # 5️⃣ JSON-Schemas ohne $ref kompilieren
      - name: Compile JSON Schemas without $ref (draft 2020-12)
        shell: bash
        run: |
          echo "🔍 Compiling JSON Schemas without $ref..."
          NOREF_SCHEMAS=$(grep -L '"\$ref"' -R schemas --include '*.json' || true)
          for f in $NOREF_SCHEMAS; do
            if [ -f "$f" ]; then
              echo "→ ajv compile $f"
              npx ajv compile --spec=draft2020 -c ajv-formats -s "$f"
            fi
          done

      # 6️⃣ JSON-Schemas mit $ref validieren (lädt Referenzen einzeln)
      - name: Validate JSON Schemas with $ref (draft 2020-12)
        shell: bash
        run: |
          echo "🔍 Validating JSON Schemas with $ref..."

          # Minimal gültiges Beispiel für person.json
          cat > /tmp/person-min.json <<'JSON'
          {
            "personIdentification": { "ahvNumber": "1234567890123", "localId": "abc" },
            "nameData": { "officialName": "Muster", "firstName": "Max" },
            "birthData": {
              "dateOfBirth": "1990-01-01",
              "placeOfBirth": { "country": "CH", "municipalityName": "Bern" },
              "sex": 1
            },
            "religionData": { "religion": 0 },
            "nationalityData": {
              "status": 2,
              "countries": [ { "country": "CH", "validFrom": "1990-01-01" } ]
            },
            "residence": {
              "reportingMunicipality": { "municipalityName": "Bern", "cantonAbbreviation": "BE" },
              "typeOfResidence": 1,
              "arrivalDate": "2020-01-01",
              "dwellingAddress": { "typeOfHousehold": 1, "validFrom": "2020-01-01" }
            }
          }
          JSON

          # Alle Schema-Dateien sammeln
          SCHEMA_FILES=($(find schemas -name '*.json' -type f))

          # Alle Schemas mit $ref finden
          REF_SCHEMAS=$(grep -l '"\$ref"' -R schemas --include '*.json' || true)
          for f in $REF_SCHEMAS; do
            echo "→ ajv validate (with refs) $f"

            # -r Parameter korrekt zusammensetzen
            REF_ARGS=""
            for ref in "${SCHEMA_FILES[@]}"; do
              REF_ARGS="$REF_ARGS -r $ref"
            done

            # Validierung mit allen Referenzen
            npx ajv validate --spec=draft2020 -c ajv-formats -s "$f" $REF_ARGS -d /tmp/person-min.json >/dev/null || \
            (echo "❌ Example may not fit $f — adjust /tmp/*.json accordingly" && exit 1)
          done

          echo "✅ All referenced schemas validated successfully."

      # 7️⃣ Abschlussmeldung
      - name: Summary
        run: echo "✅ OpenAPI and JSON Schema validation finished successfully."
